# FROM node:12.0-slim
# COPY . .
# RUN npm install
# RUN npm build
# RUN npm install -g serve

# EXPOSE 8080
# CMD ["serve","-p","8080","build/]

# FROM node:14-alpine
# # Create app directory
# WORKDIR /usr/src/react-docker-app
# # Install app dependencies
# # A wildcard is used to ensure both package.json AND package-lock.json are copied
# # where available (npm@5+)
# COPY package*.json ./
# RUN npm install
# # #To bundle your app’s source code inside the Docker image, use the COPY instruction:
# COPY . .
# #Your app binds to port 3000 so you’ll use the EXPOSE instruction to have it mapped by the docker daemon:
# EXPOSE 3000
# CMD ["npm", "start"]


FROM node:14-alpine as builder

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . ./

# Build the project and copy the files
RUN npm run build


FROM nginx:stable-alpine


COPY nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 3000 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]