FROM node:14-alpine AS build-step
WORKDIR /usr/src/app
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . ./
# EXPOSE 3000
# CMD ["npm","build"]
# RUN npm build
RUN npm run build


FROM nginx:stable-alpine
COPY --from=build-step /usr/src/app/build /usr/share/nginx/html
# COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]